from weekly_pulse.formatters.base import ReportFormatter
from weekly_pulse.models import PulseReport


class SlackMarkdownFormatter(ReportFormatter):
    """Formats a PulseReport as Slack-flavoured markdown."""

    def format(self, report: PulseReport) -> str:
        """Render the report as a Slack message string."""
        lines: list[str] = []

        lines.append(f"*📊 Weekly Pulse — {report.week}*")
        lines.append("")

        lines.append("*👥 Daily Active Users*")
        lines.append(
            f"- Avg DAU: {report.dau.avg_current:.0f}"
            f" ({report.dau.pct_change:+.1f}% vs last week)"
        )
        lines.append("")

        lines.append("*🏆 Top Modules by Volume*")
        for m in report.top_modules:
            lines.append(f"{m.rank}. {m.name} — {m.artifacts:,} artifacts")
        lines.append("")

        lines.append("*⚠️ High Error Rate Modules*")
        if report.error_flags:
            for f in report.error_flags:
                lines.append(
                    f"- {f.name} — {f.error_rate:.1%} error rate"
                    f" ({f.errors} errors / {f.artifacts:,} artifacts)"
                )
        else:
            lines.append("✅ No modules above error threshold this week.")
        lines.append("")

        lines.append("*✨ Highlight*")
        if report.highlight:
            lines.append(report.highlight)
        else:
            lines.append("_LLM highlight unavailable._")
        lines.append("")

        lines.append("---")
        lines.append("_Generated by Weekly Pulse Bot_")

        return "\n".join(lines)
